# Graph visualization settings
graph:
  # Node settings
  node:
    min_size: 10
    max_size: 30
    default_color: "#97c2fc"
    highlight_color: "#ff0000"
    
  # Edge settings
  edge:
    width: 1
    color: "#848484"
    highlight_color: "#ff0000"
    
  # Layout settings
  layout:
    hierarchical: false
    physics: true
    spring_length: 200
    spring_strength: 0.05

# Analysis settings
analysis:
  exclude_patterns:
    - "venv/*"
    - ".*"
    - "__pycache__/*"
  max_depth: 10
  include_external: false

# Output settings
output:
  format: "html"
  default_filename: "repo_visualization.html" 